name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: Prod Digital Ocean

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Droplet via SSH
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.DROPLET_USER }}
          password: ${{ secrets.DROPLET_PASSWORD }}
          port: 22
          script: |
            cd CodeMashupIWV/
            git reset --hard HEAD
            git checkout main
            git pull origin main --force
            cd website-iwv
            yarn install
            pm2 stop payload || true
            yarn build
            pm2 start payload
            
      - name: Verify deployment
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.DROPLET_USER }}
          password: ${{ secrets.DROPLET_PASSWORD }}
          port: 22
          script: |
            pm2 status payload